default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

staging:
  <<: *default
  adapter: sqlite3
  database: db/staging.sqlite3

production:
  <<: *default
  adapter: sqlite3
  database: db/production.sqlite3
